# Generated by Django 4.2.20 on 2025-08-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="slug",),
    ]
